set(DD4hep_FOUND TRUE)
set(DD4HEP_FOUND TRUE)
set(DD4hep_VERSION "1.0.0")

if(NOT TARGET DD4hep::DDCore)
  add_library(DD4hep::DDCore INTERFACE IMPORTED)
  set_target_properties(DD4hep::DDCore PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/dummy_headers")
endif()
if(NOT TARGET DD4hep::DDRec)
  add_library(DD4hep::DDRec INTERFACE IMPORTED)
  set_target_properties(DD4hep::DDRec PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/dummy_headers")
endif()
if(NOT TARGET DD4hep::DDCond)
  add_library(DD4hep::DDCond INTERFACE IMPORTED)
  set_target_properties(DD4hep::DDCond PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/dummy_headers")
endif()
if(NOT TARGET DD4hep::DDAlign)
  add_library(DD4hep::DDAlign INTERFACE IMPORTED)
  set_target_properties(DD4hep::DDAlign PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/dummy_headers")
endif()
