name: C/C++ CI LCG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        LCG: ["LCG_101/x86_64-ubuntu2004-gcc9-opt"]

    steps:
    - name: Checkout EICrecon
      uses: actions/checkout@v3
      with:
        path: EICrecon

    - name: Checkout JANA2 main
      uses: actions/checkout@v3
      with:
        repository: JeffersonLab/JANA2
        path: JANA2
    - name: Get JANA2 commit hash
      id: JANA2
      run: |
        echo "hash::$(git rev-parse HEAD)"
        echo "::set-output name=hash::$(git -C JANA2 rev-parse HEAD)"

    - uses: cvmfs-contrib/github-action-cvmfs@v2
      with:
        cvmfs_repositories: 'sft.cern.ch,geant4.cern.ch'

    - name: Cache JANA2 build
      uses: actions/cache@v3
      with:
        key: JANA2-${{ runner.os }}-${{ matrix.LCG }}-${{ steps.JANA2.outputs.hash }}
        path: JANA2/build

    - name: Build JANA2
      uses: aidasoft/run-lcg-view@v1
      with:
        release-platform: ${{ matrix.LCG }}
        run: |

          # build JANA2
          cmake -B JANA2/build -S JANA2 \
            -DCMAKE_INSTALL_PREFIX=JANA2 \
            -DCMAKE_CXX_STANDARD=17 \
            -DUSE_PYTHON=ON \
            -DUSE_ROOT=ON \
            -DUSE_XERCES=ON -DXercesC_DIR=/cvmfs/sft.cern.ch/lcg/views/LCG_101/x86_64-ubuntu2004-gcc9-opt \
            -DUSE_ZEROMQ=ON
          make -C JANA2/build install

          # build EICrecon
          ls -al EICrecon
          cmake -B EICrecon/build -S EICrecon/src \
            -DCMAKE_INSTALL_PREFIX=EICrecon \
          make -C EICrecon/build install

